import type { CheckDefinition, PillarId } from "../core/types.js";

export const PILLAR_NAMES: Record<PillarId, string> = {
  styleValidation: "Style & Validation",
  buildTasks: "Build & Tasks",
  testing: "Testing",
  documentation: "Documentation",
  devEnvironment: "Dev Environment",
  codeQuality: "Code Quality",
  observability: "Observability",
  securityGovernance: "Security & Governance",
};

export const PILLAR_ORDER: PillarId[] = [
  "styleValidation",
  "buildTasks",
  "testing",
  "documentation",
  "devEnvironment",
  "codeQuality",
  "observability",
  "securityGovernance",
];

export const DEFAULT_RUBRIC: CheckDefinition[] = [
  {
    id: "formatterConfigured",
    pillar: "styleValidation",
    name: "Formatter configured",
    weight: 3,
    remediation: "Add a formatter and expose it through a repo-root command, task target, or CI config.",
  },
  {
    id: "linterConfigured",
    pillar: "styleValidation",
    name: "Linter configured",
    weight: 4,
    remediation: "Add a linter and wire it into local validation or CI.",
  },
  {
    id: "typeOrStaticCheckConfigured",
    pillar: "styleValidation",
    name: "Type, static, or language tooling configured",
    weight: 4,
    remediation: "Add a type checker, static analyzer, or repo-local language tooling config and expose it through a command, task target, or CI config.",
  },
  {
    id: "strictModeEnabled",
    pillar: "styleValidation",
    name: "Strict mode enabled",
    weight: 3,
    remediation: "Turn on strict or hardened analysis settings where the ecosystem supports them.",
  },
  {
    id: "fastFeedbackHooks",
    pillar: "styleValidation",
    name: "Fast local feedback hooks",
    weight: 2,
    remediation: "Use pre-commit or pre-push hooks to run validation before CI.",
  },
  {
    id: "gitRepoPresent",
    pillar: "buildTasks",
    name: "Git repo present",
    weight: 2,
    remediation:
      "Scan a real git checkout, or initialize the repository with git so agents can rely on branch, diff, and review workflows.",
  },
  {
    id: "installPathDeclared",
    pillar: "buildTasks",
    name: "Install path declared",
    weight: 3,
    remediation: "Document or expose a clear install/bootstrap command at the repo root.",
  },
  {
    id: "buildOrPackageCommand",
    pillar: "buildTasks",
    name: "Build or package command",
    weight: 3,
    remediation: "Add a repo-root build or package command, task target, or equivalent build entrypoint when the repo requires one.",
  },
  {
    id: "testCommandDiscoverable",
    pillar: "buildTasks",
    name: "Test command discoverable",
    weight: 3,
    remediation: "Expose a repo-root test command or task target that works for the full codebase.",
  },
  {
    id: "validateCommandDiscoverable",
    pillar: "buildTasks",
    name: "Validation command discoverable",
    weight: 2,
    remediation: "Provide a repo-root command or task target for lint, type, or format validation.",
  },
  {
    id: "ciWorkflowPresent",
    pillar: "buildTasks",
    name: "CI workflow present",
    weight: 4,
    remediation: "Add CI config that runs validation and tests from the repository itself.",
  },
  {
    id: "testFrameworkConfigured",
    pillar: "testing",
    name: "Test framework configured",
    weight: 4,
    remediation: "Configure a test framework and make it visible from repo tooling.",
  },
  {
    id: "testFilesPresent",
    pillar: "testing",
    name: "Test files present",
    weight: 5,
    remediation: "Add representative tests that cover core source areas.",
  },
  {
    id: "testsRunnableFromRepo",
    pillar: "testing",
    name: "Tests runnable from repo root",
    weight: 3,
    remediation: "Make the full test suite runnable from the repository root.",
  },
  {
    id: "coverageSignalPresent",
    pillar: "testing",
    name: "Coverage signal present",
    weight: 1,
    remediation:
      "Optional signal for agents and reviewers. Add coverage tooling, thresholds, or published reports if you want visible test-gap reporting.",
  },
  {
    id: "integrationCoverageWhenRelevant",
    pillar: "testing",
    name: "Integration coverage where relevant",
    weight: 3,
    remediation: "Add integration, smoke, or end-to-end tests for runnable applications and services.",
  },
  {
    id: "readmePresent",
    pillar: "documentation",
    name: "README present",
    weight: 2,
    remediation: "Add a root README that explains what the repository does.",
  },
  {
    id: "setupInstructions",
    pillar: "documentation",
    name: "Setup instructions",
    weight: 4,
    remediation: "Document prerequisites and setup steps clearly enough for a newcomer or agent to follow.",
  },
  {
    id: "runAndValidateInstructions",
    pillar: "documentation",
    name: "Run and validate instructions",
    weight: 4,
    remediation: "Explain how to run the project and how to test or validate changes.",
  },
  {
    id: "envVariablesDocumented",
    pillar: "documentation",
    name: "Environment variables documented",
    weight: 2,
    remediation: "Document required environment variables and what each one is used for.",
  },
  {
    id: "contributionOrAgentGuidance",
    pillar: "documentation",
    name: "Agent workflow guidance",
    weight: 2,
    remediation: "Add AGENTS.md or equivalent agent-facing workflow guidance.",
  },
  {
    id: "sampleEnvProvided",
    pillar: "devEnvironment",
    name: "Sample environment file provided",
    weight: 3,
    remediation: "Add a sample env file when the project depends on environment variables.",
  },
  {
    id: "toolchainDeclared",
    pillar: "devEnvironment",
    name: "Toolchain declared",
    weight: 3,
    remediation: "Pin or declare the runtime or language version required to work in the repo.",
  },
  {
    id: "oneCommandStartupPath",
    pillar: "devEnvironment",
    name: "One-command startup path",
    weight: 3,
    remediation: "Expose a clear local start or dev command for the main runnable surface.",
  },
  {
    id: "clearProjectLayout",
    pillar: "codeQuality",
    name: "Clear project layout",
    weight: 3,
    remediation: "Separate source, tests, and config into recognizable locations.",
  },
  {
    id: "generatedAndVendorSeparated",
    pillar: "codeQuality",
    name: "Generated and vendor code separated",
    weight: 2,
    remediation: "Keep generated, vendored, and build output out of primary source paths.",
  },
  {
    id: "dependencyLockingPresent",
    pillar: "codeQuality",
    name: "Dependency locking present",
    weight: 2,
    remediation: "Check in lockfiles or the ecosystem equivalent for dependency pinning.",
  },
  {
    id: "staticAnalysisDepth",
    pillar: "codeQuality",
    name: "Static analysis depth",
    weight: 3,
    remediation: "Use project-specific lint or analysis rules rather than only bare defaults.",
  },
  {
    id: "loggingSignal",
    pillar: "observability",
    name: "Logging signal",
    weight: 2,
    remediation: "Adopt a centralized or structured logging approach for runtime code.",
  },
  {
    id: "healthOrDebugSignal",
    pillar: "observability",
    name: "Health or debug signal",
    weight: 2,
    remediation: "Expose health checks, diagnostics, or clear debugging workflows for runnable services.",
  },
  {
    id: "metricsTracingOrErrorReporting",
    pillar: "observability",
    name: "Metrics, tracing, or error reporting",
    weight: 2,
    remediation: "Add operational signals such as metrics, tracing, or error reporting.",
  },
  {
    id: "ownershipSignal",
    pillar: "securityGovernance",
    name: "Ownership signal",
    weight: 2,
    remediation: "Add CODEOWNERS or another explicit ownership map.",
  },
  {
    id: "licensePresent",
    pillar: "securityGovernance",
    name: "License present",
    weight: 1,
    remediation: "Add a license file or explicit package license metadata.",
  },
  {
    id: "securityScanConfigured",
    pillar: "securityGovernance",
    name: "Security scan configured",
    weight: 3,
    remediation: "Add dependency audit or security scanning in local tooling, task targets, or CI.",
  },
  {
    id: "secretHygiene",
    pillar: "securityGovernance",
    name: "Secret hygiene",
    weight: 2,
    remediation: "Add sample env files plus secret scanning or secret-ignore policy.",
  },
  {
    id: "ciSecurityStep",
    pillar: "securityGovernance",
    name: "CI security step",
    weight: 2,
    remediation: "Include at least one security-oriented job or step in CI.",
  },
];

export const MAX_SCORE = 100;
